name: Master Branch Workflow

on:
  push:
    branches:
      - master

jobs:
  action_filter:
    name: Filter Action
    runs-on: ubuntu-latest
    if: "github.event_name != 'pull_request'"
    steps:
      - name: Echo the greeting
        run: echo 'Master branch workflow triggered.'
  master_branch_action:
    name: Master Branch Actions
    runs-on: ubuntu-latest
    needs: [action_filter]
    steps:
      - uses: actions/checkout@v2
      - uses: oleksiyrudenko/gha-git-credentials@v2
        with:
          token: "${{ secrets.CICD_CREDENTIALS }}"
          name: cicd-machine-user
          email: royinx.cicd@gmail.com
      - name: Merge master to development
        run: |
          git config --global user.email "royinx.cicd@gmail.com"
          git config --global user.name "CICD-machine-user"
          git fetch --unshallow
          git checkout --track origin/development
          git checkout -b master-to-development
          git merge origin/master -s recursive -X theirs --no-edit
          git add .
          git commit -m "chore: merge from master" -a || true
          git push --set-upstream origin master-to-development
      - name: Create Pull Request
        uses: vsoch/pull-request-action@1.0.12
        env:
          PULL_REQUEST_BRANCH: "development"
          PULL_REQUEST_FROM_BRANCH: "master-to-development"
          PULL_REQUEST_TITLE: "chore: auto sync master with development"
          GITHUB_TOKEN: ${{ secrets.CICD_CREDENTIALS }}
